###
POST  http://localhost:3000/api/messages
Content-Type: application/json

{
    "user_id": 30,
    "teacher_id": 31
}

###
POST  http://localhost:3000/api/messages/new
Content-Type: application/json

{
    "user_id": 30,
    "teacher_id": 31,
    "message": "Viva el Betis"
}