# Usuarios

###
GET http://localhost:3000/api/users
###
POST http://localhost:3000/api/users/new
Content-Type: application/json

{
"name": "Albert", 
"surname": "Einstein", 
"birthdate":"2000-09-25", 
"email":"realtivida@gmail.com", 
"password":"relativo123", 
"phone":"234234334", 
"avatar":".", 
"type": "user"

}

###
DELETE http://localhost:3000/api/users/11
###
PUT http://localhost:3000/api/users/11
Content-Type: application/json

{
    "name": "aja",
    "surname": "aja",
    "birthdate": "1900-04-03",
    "email": "aja@gmail.com",
    "password": "aja",
    "phone": "858765927",
    "avatar": ""
}


# Profesores

###
GET http://localhost:3000/api/teachers
###
DELETE http://localhost:3000/api/teachers/10
###
POST http://localhost:3000/api/teachers/new
Content-Type: application/json

{
"name": "Albert", 
"surname": "Einstein", 
"birthdate":"2000-09-25", 
"email":"asdasd@gmail.com", 
"password":"relativo123", 
"phone":"234234334", 
"avatar":".", 
"type": "teacher", 
"experience": "Es relativa", 
"pricehour": 18, 
"address": "Calle pantomima", 
"active":1
}
###
PUT http://localhost:3000/api/teachers/14
Content-Type: application/json

{
    "name": "uwu",
    "surname": "uwu",
    "birthdate": "1900-04-03",
    "email": "uwu@gmail.com",
    "password": "uwu",
    "phone": "858765169",
    "avatar": "",
    "experience": "no se que hago aqui",
    "pricehour": 20.00,
    "address": "valdemoro 33",
    "acttive": false
}


# Asignaturas

###
GET http://localhost:3000/api/subjects
###
DELETE http://localhost:3000/api/subjects/1
###
POST http://localhost:3000/api/subjects/new
Content-Type: application/json

{
    "name": "matematicas",
    "level": "ESO"
}

###
PUT http://localhost:3000/api/subjects/3
Content-Type: application/json

{
    "name": "lengua",
    "level": "ESO"
}