# Usuarios

###
GET http://localhost:3000/api/users

###
GET http://localhost:3000/api/users/inactive

###
POST http://localhost:3000/api/users/email
Content-Type: application/json

{
    "email":"pepito145@gmail.com"
}

###
POST http://localhost:3000/api/users/activation
Content-Type: application/json

{
    "id":91,
    "active": 1
}

###
GET http://localhost:3000/api/users/56
###
GET http://localhost:3000/api/users/14/coments
###
GET http://localhost:3000/api/users/44/teachers
###
POST http://localhost:3000/api/users/new
Content-Type: application/json

{
"name": "Juan Carlos", 
"surname": "Primero", 
"birthdate":"2000-09-25", 
"email":"resaspñ@gmail.com", 
"password":"relativo123", 
"phone":"234234334", 
"avatar":".", 
"type": "user",
"active": 1
}

###
POST http://localhost:3000/api/users/login
Content-Type: application/json

{
"email":"kiko@gmail.com", 
"password":"test1234"
}

###
DELETE http://localhost:3000/api/users/11
###
PUT http://localhost:3000/api/users/11
Content-Type: application/json

{
    "name": "aja",
    "surname": "aja",
    "birthdate": "1900-04-03",
    "email": "aja@gmail.com",
    "password": "aja",
    "phone": "858765927",
    "avatar": ""
}

###
PUT http://localhost:3000/api/users/opinion
Content-Type: application/json

{
    "id": 4,
    "opinion": "De los mejores profesores de España actualmente",
    "score": 8
}

###
PUT http://localhost:3000/api/users/update/89
Content-Type: application/json

{
"name": "Bienhallade", 
"surname": "Dominguez", 
"birthdate":"2000-09-25", 
"email":"bienhallado@gmail.com", 
"phone":"630018709",
"avatar": "undefined"
}


# Profesores

###
GET http://localhost:3000/api/teachers
###
GET http://localhost:3000/api/teachers/profile
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjo4MCwidXNlcl9yb2xlIjoiYWRtaW4iLCJleHBfYXQiOjE2NzE1MzA2MDEsImlhdCI6MTY3MTQ0NDIwMX0.G9qGbhwJmZssm7c3B3obYY2ar3xMjCHBu2U_5Cwp_f4
###
GET http://localhost:3000/api/teachers/3/students
###
GET http://localhost:3000/api/teachers/email/marmario.giron@gmail.com
###
GET http://localhost:3000/api/teachers/inactive
###
GET http://localhost:3000/api/teachers/score/5/10

###
DELETE http://localhost:3000/api/teachers/10
###
POST http://localhost:3000/api/teachers/new
Content-Type: application/json

{
"name": "Justin", 
"surname": "Bieber", 
"birthdate":"2040-09-25", 
"email":"vivaelsisa@gmail.com", 
"password":"relativo123", 
"phone":"234234334", 
"avatar":".", 
"type": "teacher", 
"experience": "Es relativa", 
"pricehour": 18, 
"address": "Calle pantomima", 
"active":1,
"remote": 0,
"lat": 34.344543,
"long": 7.62367
}

  
###
PUT http://localhost:3000/api/teachers/71
Content-Type: application/json

{
    "name": "uwu",
    "surname": "uwu",
    "birthdate": "1900-04-03",
    "email": "uwu@gmail.com",
    "password": "uwu",
    "phone": "858765169",
    "avatar": "",
    "experience": "no se que hago aqui",
    "pricehour": 20.00,
    "address": "valdemoro 33",
    "active": false
}



### FILTROS

###
GET http://localhost:3000/api/teachers/price/5/15
###
GET http://localhost:3000/api/teachers/price/asc/5/15
###
GET http://localhost:3000/api/teachers/price/desc/5/15
###
GET http://localhost:3000/api/teachers/score/0/10
###
GET http://localhost:3000/api/teachers/3
###
GET http://localhost:3000/api/teachers/3/coments
###
GET http://localhost:3000/api/teachers/score

###
POST http://localhost:3000/api/teachers/filter
Content-Type: application/json

{
 "score": 1, 
 "city": "Calle Alcalá 45", 
 "subject":"Matematicas", 
 "price":130
}


# Asignaturas

###
GET http://localhost:3000/api/subjects
###
GET http://localhost:3000/api/subjects/distinct

###
DELETE http://localhost:3000/api/subjects/1
###
POST http://localhost:3000/api/subjects/new
Content-Type: application/json

{
    "name": "matematicas",
    "level": "ESO"
}

###
POST http://localhost:3000/api/subjects/teachers
Content-Type: application/json

{
"user_email": "juanan@gmail.com", 
"subject": "Lengua"
}

###
PUT http://localhost:3000/api/subjects/3
Content-Type: application/json

{
    "name": "lengua",
    "level": "ESO"
}